### PR TITLE
Add -Werror flag to LLVM compilation

### PR DESCRIPTION
**Pull request by akiramenai**

### CODE REVIEW

**Comment by akiramenai** [comment]
@hedgar2017 done

**Comment by hedgar2017** [comment]
> @hedgar2017 done

Thanks!
Are all warnings gone in dev-15?
Other CIs of ours depend on it and can break.

**Comment by akiramenai** [comment]
@hedgar2017 
On Mac they are gone. On our CI it's better to run before merging.

**Comment by FlashSheridan** [comment]
QA is officially delighted to run always with `-Werror`.  I would suggest bumping the version in Cargo.toml, and doing some testing of GitHub Actions with this branch on both compiler-llvm and compiler-tester, since not only is this repo public, the executable is published in the global Rust package manager.  (So theoretically it could already have a user base, some of which might theoretically object to the absence of an option to disable `-Werror`, though both seem unlikely.)

**Comment by hedgar2017** [comment]
> QA is officially delighted to run always with `-Werror`.  I would suggest bumping the version in Cargo.toml, and doing some testing of GitHub Actions with this branch on both compiler-llvm and compiler-tester, since not only is this repo public, the executable is published in the global Rust package manager.  (So theoretically it could already have a user base, some of which might theoretically object to the absence of an option to disable `-Werror`, though both seem unlikely.) 

Yes, I asked Dmitry to move it to our CI instead.
I believe this option can break a lot of platforms and clang versions.

**Comment by FlashSheridan** [comment]
> > QA is officially delighted to run always with `-Werror`.  …
> 
> Yes, I asked Dmitry to move it to our CI instead. I believe this option can break a lot of platforms and clang versions.

Agreed, reluctantly but definitively; build scripts should live in their respective repos, and having one as a public utility imposes lots of obligations on us.

**Pull request closed without merging**
