### PR TITLE
Pass arbitrary CMake options to llvm-builder

### PR DESCRIPTION
**Pull request by FlashSheridan**
Add a new option:
> --extra-args <extra-args>...    Extra arguments to pass to CMake. A leading backslash will be unescaped

Tested on Ubuntu 22.04.1 LTS Jammy Jellyfish on x86_64, our [GitHub Action](https://github.com/matter-labs/compiler-llvm/actions/runs/5159734660/jobs/9295708943), and MacOS 12.6.2 21G320 on M1 Max
Let me know if I should create some VMs to test other platforms.

### CODE REVIEW

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
Can we have a single flag for turning on building for coverage?

**Comment by FlashSheridan** [comment]
> Can we have a single flag for turning on building for coverage?

That’s the third part of CPR-973, and I’ll need to learn more Rust for it.  This part allows doing that with a slightly longer command line — currently after the “#” on the wiki instruction for building LLVM for code coverage.

**Comment by hedgar2017** [comment]
> > Can we have a single flag for turning on building for coverage?
> 
> That’s the third part of CPR-973, and I’ll need to learn more Rust for it. This part allows doing that with a slightly longer command line — currently after the “#” on the wiki instruction for building LLVM for code coverage.

The `extra-args` feature is of course useful for future development, but it looks to me like it's [a single argument here](https://www.notion.so/matterlabs/406190fd7bc0487e87d08c3c0123f24b?v=7e2950558764414c85cb41443324cfa9&pvs=4#4303d33c79b343c180471ff750cfcbf5), so it can be easily made alike to `--enable-tests`. It's just an `if` and doesn't require deep Rust knowledge, or is there something else I'm missing?

**Comment by FlashSheridan** [comment]
> so it can be easily made alike to `--enable-tests` (`--enable-coverage`). It's just an `if` and doesn't require deep Rust knowledge, 

Oh, I’m sure it‘s not rocket science, just routine variable scoping and passing issues, plus simple string and vector manipulation and assignment.  But I only just learned from _Programming Rust_ how tricky Rust’s version of “=” can be.

**Comment by hedgar2017** [comment]
> > so it can be easily made alike to `--enable-tests` (`--enable-coverage`). It's just an `if` and doesn't require deep Rust knowledge,
> 
> Oh, I’m sure it‘s not rocket science, just routine variable scoping and passing issues, plus simple string and vector manipulation and assignment. But I only just learned from _Programming Rust_ how tricky Rust’s version of “=” can be.

It's easy, just use `--enable-tests` as an example :)

**Comment by FlashSheridan** [comment]
> It's easy, just use `--enable-tests` as an example :)

I instead hacked `extra_args_unescaped` in `main_inner`.
Testing now, https://github.com/matter-labs/compiler-llvm/actions/runs/5180276071

**Comment by FlashSheridan** [comment]
> Testing verbosely now, https://github.com/matter-labs/compiler-llvm/actions/runs/5180276071

Testing with verbosity off (presumably the final commit, d5762b4) failed as well, but with a presumably unrelated “"zksolc" subprocess spawning error.”

**Comment by hedgar2017** [comment]
> > Testing verbosely now, https://github.com/matter-labs/compiler-llvm/actions/runs/5180276071
> 
> 
> 
> Testing with verbosity off (presumably the final commit, d5762b4) failed as well, but with a presumably unrelated “"zksolc" subprocess spawning error.”
> 
> 
> 
> 

Yeap, now you need zksolc and zkvyper in PATH just like solc and vyper :(

**Review by hedgar2017 — APPROVED** [review]

**Pull request merged**
